//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRapPhim.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Ve = new HashSet<Ve>();
        }
    
        public int ID { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }

        [Compare("Password",ErrorMessage ="Mật khẩu không khớp")]
        public string Confirm { get; set; }
        public string Email { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public System.DateTime NgayDangKi { get; set; }
        public bool GioiTinh { get; set; }
        public Nullable<int> DiemThuong { get; set; }
        public Nullable<int> LoaiThanhVien { get; set; }


        public bool setGioiTinh(String gioitinh) {
            if (gioitinh.Trim() == "Nam")
                return true;
            else return false;
        }
        public virtual LoaiThanhVien LoaiThanhVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ve { get; set; }
    }
}
