//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRapPhim.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.Ves = new HashSet<Ve>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Tên tài khoản không được bỏ trống")]
        public string TenTK { get; set; }
        [Required(ErrorMessage = "Mật khảu không được bỏ trống")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Họ không được bỏ trống")]
        public string Ho { get; set; }
        [Required(ErrorMessage = "Tên không được bỏ trống")]
        public string Ten { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Ngày sinh không được bỏ trống")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Ngày vào làm không được bỏ trống")]
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public bool setGioiTinh(String gioitinh)
        {
            if (gioitinh.Trim() == "Nam")
                return true;
            else
                return false;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
